name: user-console CI

env:
  node-version: 16.x
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        # with:
        #   node-version: ${{ env.node-version }}
          # cache: npm
      - name: build
        run: npx build

      # - uses: nrwl/nx-set-shas@v2
      # - run: npm ci
      # - run: npx nx workspace-lint
      # - run: npx nx format:check
      # - run: npx nx affected --target=lint --parallel=3
      # - run: npx nx affected --target=test --parallel=3 --ci --code-coverage





